/**
 * RecipeContext — shares the active pipeline data across tabs and screens.
 *
 * The Today tab sets it when the pipeline finishes.
 * The Instructions screen and Upload tab read it.
 */
import React, { createContext, useContext, useState } from 'react';

/** A single ingredient in the proposed combo. */
export interface PaninoIngredient {
  ean: string;
  productName: string;        // Original Danish
  productNameEn: string;      // Translated English (shown to user)
  productImage: string | null;
  categoryEn: string;
  newPrice: number;
  originalPrice: number;
  discount: number;
  percentDiscount: number;
  stock: number;
}

/** The recipe generated by Chef + Inspector. */
export interface GeneratedRecipe {
  name: string;
  ingredients: string[];
  steps: string[];
}

/** Full active recipe state shared across screens. */
export interface ActiveRecipe {
  panino: string;              // Recipe name (English)
  store: string;               // Winning store name
  combo: PaninoIngredient[];   // Selected ingredients with pricing
  recipe: GeneratedRecipe;     // Raw recipe JSON from AI
  instructions: string;        // Full cooking instructions text
  totalPrice: number;          // Sum of discounted prices
  totalOriginal: number;       // Sum of original prices
  totalSavings: number;        // Total money saved
}

interface RecipeContextValue {
  activeRecipe: ActiveRecipe | null;
  setActiveRecipe: (recipe: ActiveRecipe | null) => void;
}

const RecipeContext = createContext<RecipeContextValue>({
  activeRecipe: null,
  setActiveRecipe: () => {},
});

export function RecipeProvider({ children }: { children: React.ReactNode }) {
  const [activeRecipe, setActiveRecipe] = useState<ActiveRecipe | null>(null);
  return (
    <RecipeContext.Provider value={{ activeRecipe, setActiveRecipe }}>
      {children}
    </RecipeContext.Provider>
  );
}

export function useRecipe(): RecipeContextValue {
  return useContext(RecipeContext);
}
